-- Clarion runtime schema (singular table names).
-- Applied idempotently by clarion.db.migrate.ensure_schema() — once per
-- process startup and via `clarion db migrate`. Never at connect time.

CREATE TABLE IF NOT EXISTS schema_meta (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS app_setting (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS stream (
    name TEXT PRIMARY KEY,
    -- Which stream implementation handles this row ('rss', 'sitemap_news');
    -- the same enum event.source_type carries.
    source_type TEXT NOT NULL,
    config_json JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS monitoring_state (
    key TEXT PRIMARY KEY,
    value TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- The core table. One row per observed item; replaces both the old
-- `live_events` event log and the `processed_items` dedup ledger.
-- (source_type, item_id) is the natural identity — uniqueness here gives
-- us cross-restart dedup for free.
CREATE TABLE IF NOT EXISTS event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Identity
    source_type TEXT NOT NULL,
    item_id TEXT NOT NULL,
    stream_name TEXT NOT NULL,
    -- Content
    title TEXT NOT NULL,
    -- body is nullable: for sources where it duplicates title (Bluesky) or
    -- where it's just reconstituted metadata (sitemap_news), we leave it null
    -- and consumers fall back to title.
    body TEXT,
    url TEXT,
    author TEXT,
    -- Two timestamps because they drift:
    --   received_at  = when the publisher dated the item (from XML/feed/post)
    --   observed_at  = when clarion wrote this row
    received_at TIMESTAMPTZ NOT NULL,
    observed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- Source-specific bag for anything we don't filter on (Bluesky lang,
    -- RSS feed_title, raw keywords list, ...). Use JSONB so we can still
    -- spot-check via ->> when needed.
    metadata JSONB,
    UNIQUE (source_type, item_id)
);

CREATE INDEX IF NOT EXISTS event_observed_at_idx ON event (observed_at DESC);
CREATE INDEX IF NOT EXISTS event_received_at_idx ON event (received_at DESC);
CREATE INDEX IF NOT EXISTS event_stream_observed_idx ON event (stream_name, observed_at DESC);
CREATE INDEX IF NOT EXISTS event_source_observed_idx ON event (source_type, observed_at DESC);

-- Daily story clusters produced by `clarion digest build`. Rebuilt
-- idempotently per day (delete day + reinsert), so nothing outside this
-- pair of tables may reference story ids.
CREATE TABLE IF NOT EXISTS story (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- The UTC observed_at day this story was clustered under.
    day DATE NOT NULL,
    -- Representative headline (the cluster medoid's title).
    title TEXT NOT NULL,
    rep_event_id BIGINT NOT NULL REFERENCES event(id) ON DELETE CASCADE,
    event_count INTEGER NOT NULL,
    -- Distinct publication domains covering the story — the ranking signal.
    source_count INTEGER NOT NULL,
    -- Dominant language among members (from event metadata), if known.
    lang TEXT,
    built_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS story_day_rank_idx
    ON story (day, source_count DESC, event_count DESC);

CREATE TABLE IF NOT EXISTS story_event (
    story_id BIGINT NOT NULL REFERENCES story(id) ON DELETE CASCADE,
    event_id BIGINT NOT NULL REFERENCES event(id) ON DELETE CASCADE,
    -- Cosine similarity of the member event's title to the story centroid.
    similarity REAL,
    PRIMARY KEY (story_id, event_id)
);

CREATE INDEX IF NOT EXISTS story_event_event_id_idx ON story_event (event_id);

