-- Clarion runtime schema (singular table names).
-- Applied idempotently by clarion.db.migrate.ensure_schema() — once per
-- process startup and via `clarion db migrate`. Never at connect time.

CREATE TABLE IF NOT EXISTS stream (
    name TEXT PRIMARY KEY,
    -- Which stream implementation handles this row ('rss', 'sitemap_news');
    -- the same enum event.source_type carries.
    source_type TEXT NOT NULL,
    config_json JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS monitoring_state (
    key TEXT PRIMARY KEY,
    value TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- The core table. One row per observed item; replaces both the old
-- `live_events` event log and the `processed_items` dedup ledger.
-- (source_type, item_id) is the natural identity — uniqueness here gives
-- us cross-restart dedup for free.
CREATE TABLE IF NOT EXISTS event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Identity
    source_type TEXT NOT NULL,
    item_id TEXT NOT NULL,
    stream_name TEXT NOT NULL,
    -- Content
    title TEXT NOT NULL,
    -- body is nullable: news sitemaps carry no article text, and RSS
    -- bodies that just repeat the title are stored as NULL; consumers
    -- fall back to title.
    body TEXT,
    url TEXT,
    author TEXT,
    -- Two timestamps because they drift:
    --   received_at  = when the publisher dated the item (from XML/feed/post)
    --   observed_at  = when clarion wrote this row
    received_at TIMESTAMPTZ NOT NULL,
    observed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- Source-specific bag for anything we don't filter on (RSS feed_title,
    -- sitemap publication/language/keywords, ...). Use JSONB so we can
    -- still spot-check via ->> when needed.
    metadata JSONB,
    UNIQUE (source_type, item_id)
);

-- The one event index: the digest builder's day fetch and `clarion
-- status` both walk observed_at. At 100k+ rows/day every extra index
-- is real write amplification, so nothing else gets one.
CREATE INDEX IF NOT EXISTS event_observed_at_idx ON event (observed_at DESC);

-- Story clusters. The digest daemon (`clarion digest run`) grows these
-- continuously with stable ids; `clarion digest build` backfills past
-- days wholesale (delete day + reinsert).
CREATE TABLE IF NOT EXISTS story (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- The UTC day the story opened (its first event's observed_at day).
    day DATE NOT NULL,
    -- Representative headline (the member most similar to the centroid).
    title TEXT NOT NULL,
    rep_event_id BIGINT NOT NULL REFERENCES event(id) ON DELETE CASCADE,
    event_count INTEGER NOT NULL,
    -- Distinct publication domains covering the story — the ranking signal.
    source_count INTEGER NOT NULL,
    -- L2-normalized float16 title-centroid bytes; lets the daemon resume
    -- assigning to this story after a restart. NULL on pre-daemon rows.
    centroid BYTEA,
    first_seen_at TIMESTAMPTZ,
    last_seen_at TIMESTAMPTZ
);

-- Schema evolution for pre-existing databases (CREATE TABLE IF NOT
-- EXISTS won't add columns).
ALTER TABLE story ADD COLUMN IF NOT EXISTS centroid BYTEA;
ALTER TABLE story ADD COLUMN IF NOT EXISTS first_seen_at TIMESTAMPTZ;
ALTER TABLE story ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS story_last_seen_idx ON story (last_seen_at DESC);

CREATE INDEX IF NOT EXISTS story_day_rank_idx
    ON story (day, source_count DESC, event_count DESC);

CREATE TABLE IF NOT EXISTS story_event (
    story_id BIGINT NOT NULL REFERENCES story(id) ON DELETE CASCADE,
    event_id BIGINT NOT NULL REFERENCES event(id) ON DELETE CASCADE,
    -- Cosine similarity of the member event's title to the story centroid.
    similarity REAL,
    PRIMARY KEY (story_id, event_id)
);

CREATE INDEX IF NOT EXISTS story_event_event_id_idx ON story_event (event_id);

-- Title vectors for events inside the clustering window. A prunable
-- cache, not part of the permanent record: the daemon writes one row per
-- clusterable event and deletes rows that age out of the window.
-- Everything here is regenerable by re-embedding titles.
CREATE TABLE IF NOT EXISTS event_embedding (
    event_id BIGINT PRIMARY KEY REFERENCES event(id) ON DELETE CASCADE,
    -- L2-normalized float16 vector bytes (little-endian).
    vec BYTEA NOT NULL,
    -- Denormalized from event so pruning needs no join.
    observed_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS event_embedding_observed_idx ON event_embedding (observed_at);

